# Gradle runtime options
org.gradle.daemon = true
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

# Java / Hytale options
java_version = 25
hytale_version = 0.+
patchline = release

# Mod identity
group = dev.galysso.talentgraph
manifest_group = Galysso
mod_name = TalentGraph
mod_id = talentgraph
main_class = dev.galysso.talentgraph.TalentGraphPlugin
mod_author = Jocelin
mod_license = MIT
mod_description = Create and use talent graphs.
mod_url = https://github.com/galysso/talent-graph
version = 0.1.0

# Manifest / packaging options
includes_pack = true
disabled_by_default = false
server_version = 0.6.5
manifestServerVersion = >=0.6.0 <0.7.0
manifest_dependencies = 
manifest_opt_dependencies = 
curseforgeID = 

# Tooling
injectServerJavadocsIntoSources = true
generateAssetsBinary = false
